const SUPABASE_URL = "https://jdqnjxacnwmmomvvwmxy.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkcW5qeGFjbndtbW9tdnZ3bXh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEwNjEwMjQsImV4cCI6MjEwNjYzNzAyNH0.FBIwh-OFeX-aAMkyG346VPI47mOtuECrkQw7PgpnlLM";

var supabaseApp = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
